name: DeathStats
version: '1.0'
main: org.minecraft.tsunami.deathStats.Main
api-version: '1.21'
description: Track and display player deaths

commands:
  deathstats:
    description: Manage death statistics
    usage: |
      /deathstats help - Show help information
      /deathstats check <player> - Check a player's death statistics
      /deathstats reset <player> - Reset deaths for a specific player
      /deathstats top - Show the death statistics leaderboard
      /deathstats toggle - Toggle death statistics scoreboard
    aliases: [ds]
    permission: deathstats.use

permissions:
  deathstats.use:
    description: Allows using DeathStats commands
    default: true

  deathstats.check:
    description: Allows checking player death statistics
    default: op

  deathstats.reset:
    description: Allows resetting player deaths
    default: op

  deathstats.top:
    description: Allows seeing the death statistics leaderboard
    default: true

  deathstats.toggle:
    description: Allows seeing the death statistics leaderboard
    default: op
