name: DeathStats
version: '1.3'
main: org.minecraft.tsunami.deathStats.Main
api-version: '1.17' # Minimum supported version
author: Tsunami
description: A plugin that lets you follow up on player's death statistics with simple leaderboard and sidebar.

commands:
  deathstats:
    description: Base command for DeathStats.
    usage: /<command> help
    aliases: [ds]
    permission: deathstats.use

permissions:
  deathstats.use:
    description: Allows using any DeathStats command (if sub-permissions aren't met).
    default: true
  deathstats.help:
    description: Allows using /ds help.
    default: true
  deathstats.check:
    description: Allows checking player death statistics (/ds check [player]).
    default: true
  deathstats.check.others:
    description: Allows checking other players' death statistics (/ds check <player>).
    default: op
  deathstats.set:
    description: Allows setting a player's deaths (/ds set <player> <amount>).
    default: op
  deathstats.reset:
    description: Allows resetting a player's deaths (/ds reset <player>).
    default: op
  deathstats.top:
    description: Allows seeing the death statistics leaderboard (/ds top).
    default: true
  deathstats.scoreboard.enable:
    description: Allows enabling the death scoreboard (/ds enable scoreboard).
    default: op
  deathstats.scoreboard.disable:
    description: Allows disabling the death scoreboard (/ds disable scoreboard).
    default: op
  deathstats.health.enable:
    description: Allows enabling health displays (/ds enable <tab|belowname>).
    default: op
  deathstats.health.disable:
    description: Allows disabling health displays (/ds disable <tab|belowname>).
    default: op
  deathstats.reload:
    description: Allows reloading the plugin configuration (/ds reload).
    default: op
  deathstats.admin:
    description: Grants all DeathStats permissions.
    default: op
    children:
      deathstats.use: true
      deathstats.help: true
      deathstats.check: true
      deathstats.check.others: true
      deathstats.set: true
      deathstats.reset: true
      deathstats.top: true
      deathstats.scoreboard.enable: true
      deathstats.scoreboard.disable: true
      deathstats.health.enable: true
      deathstats.health.disable: true
      deathstats.reload: true